language: ruby
rvm:
- 2.4.2
cache: bundler
sudo: false
before_script: bundle exec rake db:create db:migrate
deploy:
  provider: heroku
  api_key:
    secure: 6Sf164eH3eMAMhkZnI2Lpir7jXFvYVQzcCucWEPZlw9MGKe75BGkVbcgKziWz2qC51HjrZMZzUXd8u5re4EUZjlrM0V5pegigq8qkD8cyBXWNgO3QAOPRBu84suVNkS8IAy7h/lshc0c65Xido2BJ11ErLaaDXL0zskraJ4Nj6pCtVosm6TE8dLdnrbYR1qhCeRkXZnPJF+w7ychaayiOpwevEweGrvXd2vJxentzzbIWam9SjmzasACTaggLzu1bj+EnOoqq9Y9y/K2mAM5l5ktEhkecloFoKaunRuT3IlvFEoiDgiq8oqSkC8Eom5z8Pjv6DUN50LxwebmTTW2uAWmSeHJCm265IgyZVM/9CqxOP6heQme1OcGQdaghQo0GaWxnII6p0yqShdx2jfguKSHpHj8bC721c86tfgTxf2wyspKhEKywV9g4q/gwtaDO1V0hftAn0HwNXR+l3M1PfDLlftHgBLrAybKYwqJueeD9vlUSWfMXjbnk+AjqlLxMlJkxbM87JP+MHrbIzgCQeeeDMPZD04vSydxJjpDVZaN/50uAP0rlVcNAYvh1mwIh1EJDgKKZdAIqRJRbebCNF1B47bVHNxY+f/YEv8bmt0cPSp36KcC1VgyiMrzHfRAZi74678+jt7v/+RgvNDJFImkc/MuAIUs1lb2fasBIHs=
notifications:
  email:
  - apolishc@gmail.com
  - emhanson08@gmail.com
  - tespintom@icloud.com
  - mccool.derek@yahoo.com
  - lucillevsam@gmail.com
  - jaredschil@gmail.com
